# Generated by Django 5.1.1 on 2025-05-14 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('check_in_type', models.IntegerField(default=1, null=True)),
                ('check_out_type', models.IntegerField(default=1, null=True)),
                ('check_in_by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_by_teacher', to='school.teacher')),
                ('check_out_by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_out_by_teacher', to='school.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_used_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
