# Generated by Django 5.1.1 on 2025-05-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todayes_teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbatch', to='school.batch')),
                ('subject_class_and_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class_and_teacher', to='school.subject_class_and_teacher')),
            ],
        ),
    ]
