# Generated by Django 5.1.1 on 2025-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_todayes_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayes_teaching',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
