# Generated by Django 5.2.1 on 2025-05-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_detail',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='school.batch'),
        ),
        migrations.AddField(
            model_name='admin_detail',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admin_detail',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admin_detail',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Admin_login',
        ),
    ]
