# Generated by Django 5.2.1 on 2025-05-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_admin_detail_batch_admin_detail_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_detail',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='admin_detail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='admin_detail',
            name='qualification',
        ),
    ]
