# Generated by Django 5.1.1 on 2025-05-21 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('edit_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('pin', models.CharField(max_length=10, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='school.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('secret_pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerks', to='school.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transfer_To_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_admin', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bank_account')),
                ('from_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transfer_To_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('from_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Account_Opening_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bank_account')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.AddField(
            model_name='bank_account',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk'),
        ),
        migrations.CreateModel(
            name='Clerk_used_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.IntegerField(default=0)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Debit_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('order_by', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_credit_debit_category', to='school.clerk')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_credit_debit_category', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('check_number', models.CharField(max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_clerk', to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_bank', to='school.bank_account')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_clerk', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='School_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('aadhar_number', models.IntegerField(unique=True)),
                ('secret_pin', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('edit_status', models.IntegerField(default=1)),
                ('tocken', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(max_length=100, null=True)),
                ('by_admin', models.IntegerField(default=0)),
                ('to_school', models.IntegerField(default=0)),
                ('to_all_teachers', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='school.batch')),
                ('by_clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_clerk', to='school.clerk')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='school.school_class')),
                ('to_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_student', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Class_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('veryfy_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_student_fee', to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('veryfy_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veryfy_by_student_fee', to='school.admin_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='student_images')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_received_Fee_Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_amount', models.FloatField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('veryfy_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_student_received_fee', to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_student_received_fee', to='school.clerk')),
                ('veryfy_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veryfy_by_student_received_fee', to='school.admin_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Student_recived_Fee_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived_amount', models.FloatField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bank_account')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_student_recived_fee', to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_student_recived_fee', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('aadhar_number', models.IntegerField(null=True, unique=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='teacher_images')),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('branding_status', models.IntegerField(default=0, null=True)),
                ('about_you', models.TextField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.batch')),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clerk', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_class_and_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Readed_Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_by_admin', models.IntegerField(default=0)),
                ('readed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by_notice', to='school.notice')),
                ('read_by_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by_student', to='school.student')),
                ('read_by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_bby_teacher', to='school.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='by_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_teacher', to='school.teacher'),
        ),
        migrations.AddField(
            model_name='notice',
            name='to_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_teacher', to='school.teacher'),
        ),
        migrations.CreateModel(
            name='Class_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
