# Generated by Django 5.2.1 on 2025-05-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk_used_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.IntegerField(default=0)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
    ]
