# Generated by Django 5.2.1 on 2025-05-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_clerk_used_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('aadhar_number', models.IntegerField(unique=True)),
                ('secret_pin', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('edit_status', models.IntegerField(default=1)),
                ('tocken', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='student_images')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
