# Generated by Django 5.2.1 on 2025-05-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('aadhar_number', models.IntegerField(null=True, unique=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='teacher_images')),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('branding_status', models.IntegerField(default=0, null=True)),
                ('about_you', models.TextField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.batch')),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clerk', to='school.clerk')),
            ],
        ),
    ]
