# Generated by Django 5.2.1 on 2025-05-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transfer_To_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('from_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transfer_To_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_admin', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('from_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('check_number', models.CharField(max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_clerk', to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_bank', to='school.bank_account')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_clerk', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(max_length=100, null=True)),
                ('by_admin', models.IntegerField(default=0)),
                ('to_school', models.IntegerField(default=0)),
                ('to_all_teachers', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='school.batch')),
                ('by_clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_clerk', to='school.clerk')),
                ('by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_teacher', to='school.teacher')),
                ('to_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_student', to='school.student')),
                ('to_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_teacher', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Readed_Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_by_admin', models.IntegerField(default=0)),
                ('readed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by_notice', to='school.notice')),
                ('read_by_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by_student', to='school.student')),
                ('read_by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_bby_teacher', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='School_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='to_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='school.school_class'),
        ),
        migrations.CreateModel(
            name='Class_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
            ],
        ),
        migrations.CreateModel(
            name='Class_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
            ],
        ),
        migrations.CreateModel(
            name='Student_received_Fee_Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_amount', models.FloatField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_student_received_fee', to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_student_received_fee', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Student_recived_Fee_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived_amount', models.FloatField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bank_account')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_student_recived_fee', to='school.clerk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_student_recived_fee', to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_class_and_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.clerk')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
